name: JadedCore
version: '${project.version}'
main: net.jadedmc.jadedcore.JadedCore
api-version: 1.19
depend: [ PlaceholderAPI ]
authors: [ JadedMC ]
website: http://www.jadedmc.net

softdepend:
  - DiscordSRV

commands:
  api:
    description: Runs the api key command.
    usage: /api
  broadcast:
    description: Broadcast command.
    usage: /broadcast
  chatlog:
    description: View the chat logs of a player.
    usage: /chatlog
    permission: jadedcore.chatlog
  alts:
    description: View a list of player alts.
    usage: /alts
    permission: jadedcore.alts
  fakejoin:
    description: Send a fake join message
    usage: /<command>
    aliases: [fj]
    permission: jadedcore.fakejoin
  fakequit:
    description: Send a fake quit message
    usage: /<command>
    aliases: [fq]
    permission: jadedcore.fakequit
  uuid:
    description: View a player's uuid.
    usage: /<command>
    permission: jadedcore.uuid
  vanish:
    description: Toggle vanish mode.
    usage: /<command>
    aliases: [v]
    permission: jadedcore.vanish
  games:
    description: View the games available on the server.
    usage: /<command>
  commandspy:
    description: Spy on commands.
    usage: /<command>
    aliases: [cmdspy]
    permission: jadedcore.commandspy