name: JadedCore
version: '${project.version}'
main: net.jadedmc.jadedcore.JadedCorePlugin
api-version: 1.19
depend: [ PlaceholderAPI, LuckPerms , JadedChat]
authors: [ JadedMC ]
website: http://www.jadedmc.net

softdepend:
  - DiscordSRV

commands:
  alts:
    description: View a list of player alts.
    usage: /alts
    permission: jadedcore.alts
  api:
    description: Runs the api key command.
    usage: /api
  broadcast:
    description: Broadcast command.
    usage: /broadcast
    aliases: [bc]
    permission: jadecore.broadcast
  chatlog:
    description: View the chat logs of a player.
    usage: /chatlog
    permission: jadedcore.chatlog
  commandspy:
    description: Spy on commands.
    usage: /<command>
    aliases: [ cmdspy ]
    permission: jadedcore.commandspy
  ecsee:
    description: View someone's enderchest.
    usage: /<command>
    permission: jadedcore.ecsee
  enderchest:
    description: View your own enderchest.
    usage: /<command>
    aliases: [ec]
    permission: jadedcore.enderchest
  feed:
    description: Fill a player's hunger and saturation bars.
    usage: /<command>
    permission: jadedcore.feed
  fly:
    description: Toggles flight
    usage: /<command>
    permission: jadedcore.fly
  games:
    description: View the games available on the server.
    usage: /<command>
    aliases: [play]
  heal:
    description: Heals a player
    usage: /<command>
    permission: jadedcore.heal
  invsee:
    description: View a player's inventory.
    usage: /<command>
    permission: jadedcore.invsee
  rename:
    description: Rename an item in the player's hand.
    usage: /<command>
    permission: jadedcore.rename
  uuid:
    description: View a player's uuid.
    usage: /<command>
    permission: jadedcore.uuid
  vanish:
    description: Toggle vanish mode.
    usage: /<command>
    aliases: [v]
    permission: jadedcore.vanish
  workbench:
    description: Opens a crafting table.
    usage: /<command>
    aliases: [wb,craft]
    permission: jadedcore.workbench
  center:
    description: Center yourself on a block.
    permission: jadedcore.center
  rules:
    description: View the server rules.
  discord:
    description: View the server discord.
  rank:
    description: Debug command for the rank system.
  profile:
    description: View a player's profile.
  website:
    description: View a link to the server website.
  store:
    description: View a link to the server store.